/**
 * Audio — synthesised, not sampled.
 *
 * Every sound in the game is generated by the Web Audio API at the moment it
 * plays. There are no audio files: nothing to download, nothing to license,
 * nothing to keep in sync with the repo. It is the same bet the character rigs
 * make — build it out of primitives and it costs bytes instead of assets.
 *
 * It also buys something a sample library cannot: every sound takes a `pitch`,
 * so the same recipe gives each character its own voice. The kangaroo's punch
 * and the shark's torpedo are the same three lines of synthesis at different
 * frequencies.
 *
 * Depends on the browser's audio clock, not on any renderer — the 2D build can
 * use this file unchanged.
 */

/** Recipes. Each is a function of (audio, ctx, when, opts) that wires nodes. */
const RECIPES = {
  /* ---------------- weapons ---------------- */

  shoot(a, ctx, t, o) {
    const pitch = o.pitch || 1;
    // Body: a fast downward blip. The drop is what makes it read as a shot
    // rather than as a beep.
    a.tone({ type: 'sawtooth', from: 780 * pitch, to: 190 * pitch, dur: 0.14,
             gain: 0.5, curve: 'exp', at: t });
    // Attack transient: without the click on the front the shot sounds soft
    // no matter how loud the body is.
    a.noise({ dur: 0.05, gain: 0.45, filter: 'highpass', freq: 1400, at: t });
  },

  swing(a, ctx, t, o) {
    const pitch = o.pitch || 1;
    a.noise({ dur: 0.22, gain: 1.9, filter: 'bandpass', q: 1.4,
              freq: 500 * pitch, freqTo: 2400 * pitch, at: t });
  },

  /**
   * A footfall. Very quiet by design — it plays about twice a second for the
   * whole match, so anything with presence becomes a drill.
   */
  step(a, ctx, t, o) {
    const pitch = o.pitch || 1;
    a.noise({ dur: 0.07, gain: 0.34, filter: 'lowpass',
              freq: 900 * pitch, freqTo: 260 * pitch, at: t });
    a.tone({ type: 'sine', from: 130 * pitch, to: 70 * pitch, dur: 0.06,
             gain: 0.16, at: t });
  },

  /* ---------------- impacts ---------------- */

  hit(a, ctx, t, o) {
    const pitch = o.pitch || 1;
    a.noise({ dur: 0.12, gain: 0.62, filter: 'bandpass', q: 0.8,
              freq: 1800 * pitch, freqTo: 420 * pitch, at: t });
    a.tone({ type: 'triangle', from: 200 * pitch, to: 90 * pitch, dur: 0.1,
             gain: 0.45, at: t });
  },

  hurt(a, ctx, t) {
    // Duller and lower than `hit` on purpose: taking damage and dealing it must
    // never be confused in the middle of a fight.
    a.tone({ type: 'square', from: 240, to: 110, dur: 0.18, gain: 0.5, at: t });
    a.noise({ dur: 0.16, gain: 0.32, filter: 'lowpass', freq: 900, at: t });
  },

  explosion(a, ctx, t, o) {
    const size = o.size || 1;
    a.noise({ dur: 0.55 * size, gain: 0.4, filter: 'lowpass',
              freq: 2200, freqTo: 160, at: t });
    // The sub is what you feel rather than hear; without it a big blast and a
    // small one sound like the same crackle at different volumes.
    a.tone({ type: 'sine', from: 120, to: 34, dur: 0.5 * size, gain: 0.5,
             curve: 'exp', at: t });
  },

  /* ---------------- abilities ---------------- */

  ultimate(a, ctx, t, o) {
    const pitch = o.pitch || 1;
    a.tone({ type: 'sawtooth', from: 160 * pitch, to: 900 * pitch, dur: 0.42,
             gain: 0.26, curve: 'exp', at: t });
    a.tone({ type: 'square', from: 240 * pitch, to: 1350 * pitch, dur: 0.42,
             gain: 0.12, curve: 'exp', at: t });
    a.noise({ dur: 0.45, gain: 0.18, filter: 'highpass',
              freq: 300, freqTo: 5000, at: t });
  },

  dash(a, ctx, t) {
    a.noise({ dur: 0.3, gain: 2.6, filter: 'bandpass', q: 2.2,
              freq: 260, freqTo: 1800, at: t });
  },

  /* ---------------- life cycle ---------------- */

  death(a, ctx, t) {
    a.tone({ type: 'sawtooth', from: 420, to: 70, dur: 0.55, gain: 0.3,
             curve: 'exp', at: t });
    a.noise({ dur: 0.4, gain: 0.2, filter: 'lowpass', freq: 1800, freqTo: 200, at: t });
  },

  respawn(a, ctx, t) {
    a.arpeggio([392, 523, 659], 0.075, { type: 'triangle', gain: 0.2, dur: 0.14, at: t });
  },

  /* ---------------- pickups and hazards ---------------- */

  dropLand(a, ctx, t) {
    a.tone({ type: 'sine', from: 90, to: 45, dur: 0.28, gain: 0.4, curve: 'exp', at: t });
    a.noise({ dur: 0.18, gain: 0.2, filter: 'bandpass', q: 1.2, freq: 1200, at: t });
  },

  pickup(a, ctx, t) {
    a.arpeggio([659, 880, 1175], 0.06, { type: 'triangle', gain: 0.22, dur: 0.13, at: t });
  },

  warning(a, ctx, t) {
    // The meteor telegraph. Deliberately a two-note stab rather than a siren:
    // it has to be readable while three other things are exploding.
    a.tone({ type: 'square', from: 330, to: 330, dur: 0.09, gain: 0.16, at: t });
    a.tone({ type: 'square', from: 247, to: 247, dur: 0.11, gain: 0.16, at: t + 0.12 });
  },

  /* ---------------- match and UI ---------------- */

  countdown(a, ctx, t) {
    a.tone({ type: 'square', from: 440, to: 440, dur: 0.11, gain: 0.42, at: t });
  },

  go(a, ctx, t) {
    a.tone({ type: 'square', from: 880, to: 880, dur: 0.22, gain: 0.38, at: t });
    a.tone({ type: 'triangle', from: 1320, to: 1320, dur: 0.22, gain: 0.2, at: t });
  },

  score(a, ctx, t) {
    a.arpeggio([523, 784], 0.07, { type: 'triangle', gain: 0.2, dur: 0.12, at: t });
  },

  win(a, ctx, t) {
    a.arpeggio([523, 659, 784, 1047], 0.12, { type: 'triangle', gain: 0.26, dur: 0.4, at: t });
  },

  lose(a, ctx, t) {
    a.arpeggio([440, 392, 311, 262], 0.14, { type: 'sawtooth', gain: 0.2, dur: 0.45, at: t });
  },

  click(a, ctx, t) {
    a.tone({ type: 'triangle', from: 700, to: 700, dur: 0.05, gain: 0.26, at: t });
  },

  select(a, ctx, t) {
    a.arpeggio([587, 880], 0.05, { type: 'triangle', gain: 0.16, dur: 0.1, at: t });
  },

  reload(a, ctx, t) {
    a.tone({ type: 'square', from: 1300, to: 1300, dur: 0.035, gain: 0.2, at: t });
  }
};

/**
 * How often the same sound may retrigger, in seconds.
 *
 * A twelve-shard ultimate lands twelve explosions in the same frame. Playing
 * all twelve is not louder, it is just distorted — and on a phone it is a stall.
 */
const MIN_GAP = {
  step: 0.11,
  hit: 0.04,
  hurt: 0.09,
  explosion: 0.07,
  shoot: 0.04,
  reload: 0.03,
  warning: 0.25
};

export class Audio {
  constructor(opts = {}) {
    this.enabled = opts.enabled !== false;
    this.volume = opts.volume == null ? 0.85 : opts.volume;
    this.ctx = null;
    this.master = null;
    this.noiseBuffer = null;
    this._last = Object.create(null);
    this._unlockBound = null;
    // An OfflineAudioContext can be passed in so the sounds can be rendered and
    // measured in a test instead of only being listened to.
    this._injected = opts.context || null;
  }

  /**
   * Browsers refuse to start audio without a gesture, so the context is built
   * on the first touch or key rather than at boot — creating it earlier just
   * produces a suspended context and a console warning.
   */
  attachUnlock(target = window) {
    if (this._unlockBound) return;
    this._unlockBound = () => this.unlock();
    ['pointerdown', 'keydown', 'touchstart'].forEach((ev) => {
      target.addEventListener(ev, this._unlockBound, { passive: true });
    });
  }

  unlock() {
    try {
      if (!this.ctx) this.build();
      if (this.ctx.state === 'suspended') this.ctx.resume();
    } catch (err) {
      console.warn('[BrawlZ] audio unavailable —', err.message);
      this.enabled = false;
    }
  }

  build() {
    if (this._injected) {
      this.ctx = this._injected;
    } else {
      const Ctx = window.AudioContext || window.webkitAudioContext;
      if (!Ctx) throw new Error('no Web Audio');
      this.ctx = new Ctx();
    }

    // A compressor on the master bus is the cheapest way to survive a busy
    // moment: six things exploding at once stay loud instead of clipping.
    const comp = this.ctx.createDynamicsCompressor();
    comp.threshold.value = -14;
    comp.knee.value = 24;
    comp.ratio.value = 8;
    comp.attack.value = 0.004;
    comp.release.value = 0.2;

    this.master = this.ctx.createGain();
    this.master.gain.value = this.enabled ? this.volume : 0;
    this.master.connect(comp);
    comp.connect(this.ctx.destination);

    this.noiseBuffer = this.makeNoise(1.2);
  }

  makeNoise(seconds) {
    const rate = this.ctx.sampleRate;
    const buf = this.ctx.createBuffer(1, Math.floor(rate * seconds), rate);
    const data = buf.getChannelData(0);
    for (let i = 0; i < data.length; i++) data[i] = Math.random() * 2 - 1;
    return buf;
  }

  setEnabled(on) {
    this.enabled = on;
    if (!this.master) return;
    const now = this.ctx.currentTime;
    this.master.gain.cancelScheduledValues(now);
    this.master.gain.setTargetAtTime(on ? this.volume : 0, now, 0.02);
  }

  /* ------------------------------------------------------------------ */

  /** Plays a recipe by name. Unknown names are ignored, never thrown. */
  play(name, opts = {}) {
    if (!this.enabled || !this.ctx) return false;
    const recipe = RECIPES[name];
    if (!recipe) return false;

    const now = this.ctx.currentTime;
    const gap = MIN_GAP[name];
    if (gap && this._last[name] != null && now - this._last[name] < gap) return false;
    this._last[name] = now;

    recipe(this, this.ctx, now, opts);
    return true;
  }

  /* ---------------- synthesis primitives ---------------- */

  /**
   * One oscillator with a frequency ramp and a percussive envelope.
   *
   * The envelope always ends at a tiny non-zero value: exponential ramps to
   * exactly zero are undefined in Web Audio and produce a click.
   */
  tone({ type = 'sine', from = 440, to = null, dur = 0.2, gain = 0.2,
         curve = 'linear', at = 0 }) {
    const ctx = this.ctx;
    const osc = ctx.createOscillator();
    const amp = ctx.createGain();

    osc.type = type;
    osc.frequency.setValueAtTime(from, at);
    if (to != null && to !== from) {
      if (curve === 'exp') osc.frequency.exponentialRampToValueAtTime(Math.max(1, to), at + dur);
      else osc.frequency.linearRampToValueAtTime(Math.max(1, to), at + dur);
    }

    amp.gain.setValueAtTime(0.0001, at);
    amp.gain.exponentialRampToValueAtTime(gain, at + Math.min(0.012, dur * 0.2));
    amp.gain.exponentialRampToValueAtTime(0.0001, at + dur);

    osc.connect(amp);
    amp.connect(this.master);
    osc.start(at);
    osc.stop(at + dur + 0.02);
    return osc;
  }

  /** A burst of noise through a sweeping filter — every impact in the game. */
  noise({ dur = 0.2, gain = 0.2, filter = 'lowpass', freq = 1000,
          freqTo = null, q = 1, at = 0 }) {
    const ctx = this.ctx;
    const src = ctx.createBufferSource();
    src.buffer = this.noiseBuffer;
    // Start at a random offset so repeated hits are not literally identical.
    const offset = Math.random() * Math.max(0, this.noiseBuffer.duration - dur);

    const biquad = ctx.createBiquadFilter();
    biquad.type = filter;
    biquad.Q.value = q;
    biquad.frequency.setValueAtTime(freq, at);
    if (freqTo != null && freqTo !== freq) {
      biquad.frequency.exponentialRampToValueAtTime(Math.max(20, freqTo), at + dur);
    }

    const amp = ctx.createGain();
    amp.gain.setValueAtTime(0.0001, at);
    amp.gain.exponentialRampToValueAtTime(gain, at + Math.min(0.008, dur * 0.15));
    amp.gain.exponentialRampToValueAtTime(0.0001, at + dur);

    src.connect(biquad);
    biquad.connect(amp);
    amp.connect(this.master);
    src.start(at, offset, dur + 0.02);
    return src;
  }

  arpeggio(freqs, step, { type = 'triangle', gain = 0.2, dur = 0.15, at = 0 }) {
    freqs.forEach((f, i) => {
      this.tone({ type, from: f, to: f, dur, gain, at: at + i * step });
    });
  }
}

export const SOUND_NAMES = Object.keys(RECIPES);
